# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build vuepress wiki.projectbw.ru

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - run: yarn install --frozen-lockfile
    - run: yarn docs:build  

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist
        fqdn: wiki.projectbw.ru
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: telegramm send
      #uses: robotomize/notify-telegram@v0.1.0
      #if: always()
      #with:
        #chat: ${{ secrets.chat }} # user id or channel name secret
        #token: ${{ secrets.token }} # token secret
        #status: ${{ job.status }} # do not modify this line
        #message: ${{ secrets.message }} # custom message

        
